

YR_SD_RUNTIME_VERIF="yr_sd_runtime_verif"

YR_SD_RUNTIME_VERIF_HOME_DEVEL="${HOME}/${YR_SD_RUNTIME_VERIF}"

rm -rf ${YR_SD_RUNTIME_VERIF}

cp -r ${YR_SD_RUNTIME_VERIF_HOME_DEVEL} .

rm -rf ${YR_SD_RUNTIME_VERIF_HOME_DEVEL}/.git


